name: Isle of Man
favicon: null
layout_spectrum: 0.06063935626298189
typography_spectrum: 0.11960877245292068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4382761081214994
  lightness: 0.41203977447003126
  saturation: 0.2026870131958276
  rhythmicContrast: 0.7321266192011535
purpose: []
